### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [Shawn-Williams/Jammming-CA#6]
The project came out very well. I liked how it started off by requiring the user to first connect to spotify. The prompt that showed the playList was saved successfully was also good. The user interface and experience was on point. Very good attention to detail and logic flow. The only thing I would suggest is doing some more research on how state flows in react. Here is a reference; 
https://reactjs.org/docs/state-and-lifecycle.html

**Comment by Shawn-Williams** [comment]
Thank you!
